from .user.common_function import *
from .user.login import *
from .user.register import *
from .user.forget_password import *
from .user.reviews import *
from .user.change_password import *
from .user.contactus import *
from .user.update_user import *
from .user.register_ai import *
from .user.profile import *
from .user.update_review import *
from .user.mydevice_details import *
from .user.premium_user import *
from .user.logined_user_detils import *
from .user.auth import *
from .user.kyc import *