from .user.common_function import *
from .user.login import *
from .user.register import *
from .user.forget_password import *
from .user.reviews import *
from .user.change_password import *
from .user.contactus import *
from .user.update_user import *
from .user.register_ai import *
from .user.profile import *